# Generated by Django 2.2.6 on 2019-10-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField(verbose_name='Event date:')),
                ('event_venue', models.CharField(max_length=200)),
                ('event_image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
